config {
    type: "table",
    name: "output-grouped",
    description: "Generating the grouped by session data for later attribution."
}

SELECT
  JSON_VALUE(user.device) AS journey_id,
  JSON_VALUE(user.session) AS visit_id,
  STRING_AGG(event) AS agg_events,
  MAX(
  IF
    (event = 'session start', JSON_VALUE(data.source), NULL)) AS agg_source, --CampaignLevel1
  MAX(
  IF
    (event = 'session start', JSON_VALUE(data.referrer), NULL)) AS agg_referrer,
  --  SPLIT(STRING_AGG(COALESCE(campaign_name, JSON_VALUE(events.data.campaign))), ",")[SAFE_OFFSET(0)] AS agg_campaign,
  MAX(
  IF
    (event = 'session start', COALESCE(campaign_name, JSON_VALUE(events.data.campaign)), NULL)) AS agg_campaign,
  MAX(
  IF
    (event = 'session start', JSON_VALUE(events.data.campaign), NULL)) AS campaign_id,
  MAX(
    IF(
      event = 'se ssion start',
      IF(medium = 'direct', '(direct)', medium),
      NULL
    )
  ) AS agg_medium, -- CampaignType
  MAX(
  IF
    (event = 'order complete', JSON_VALUE(data.order_id), NULL)) AS order_id_agg,
  MAX(
  IF
    (event = 'session start', events.marketing, NULL)) AS agg_marketing,
  MAX(
  IF
    (event = 'session start', channel_group, NULL)) AS agg_channel_group, --ChannelGroupingName
  MAX(
  IF
    (event = 'session start', isPaid, NULL)) AS agg_isPaid,
  DATETIME(MAX(timestamp), "Europe/Berlin") AS date,
  COUNT(*) AS cnt
FROM
  ${ref("attribution-str_channel_grouping")} events
LEFT JOIN
  ${ref("data-str_ga4_campaign_names")} g_campaigns
ON
  JSON_VALUE(events.data.source) like "%google%"
  AND SAFE_CAST(JSON_VALUE(events.data.campaign) AS INT) = g_campaigns.campaign_id
WHERE
  JSON_VALUE(user.device) IS NOT NULL
  AND (timestamp >= '2025-05-01'
    OR timestamp IS NULL)
GROUP BY
  JSON_VALUE(user.device),
  JSON_VALUE(user.session)
HAVING
  MAX(timestamp) IS NOT NULL
