config {
    type: "view",
    name: "attribution-channel_grouping"
}


SELECT
s.id,
  s.event,
  s.user,
  s.data as data_all,



  dss.isPaid,
dss.timestamp,
dss.data,
dss.session_id,

  dss.channel_group,
  dss.source_id,
  dss.source_previous_id,
  dss.marketing
FROM
      `api-project-726829680648.walkerOS.events` s
LEFT JOIN
  ${ref("data-session_start")} dss
ON
  s.id = dss.event_id
  AND s.timestamp = dss.timestamp


WHERE
  1=1
  AND s.timestamp >='2024-01-01'
  --AND DATE(s.timestamp) >= DATE_SUB(CURRENT_DATE(), INTERVAL 2 DAY)
ORDER BY
  event_id
