config {
  type: "view",
  name: "data-sessions",
  description: "Resolved data object",
}


SELECT
  events.timestamp,
  events.id as event_id,
  NULLIF(JSON_EXTRACT_SCALAR(user, '$.session'), "") as session_id,
  NULLIF(JSON_EXTRACT_SCALAR(data, '$.id'), "") as id,
  NULLIF(JSON_EXTRACT_SCALAR(user, '$.device'), "") as device,
  NULLIF(JSON_EXTRACT_SCALAR(data, '$.marketing'), "") as marketing,
  NULLIF(JSON_EXTRACT_SCALAR(data, '$.source'), "") as source, -- UTM
  NULLIF(JSON_EXTRACT_SCALAR(data, '$.medium'), "") as medium, -- UTM
  NULLIF(JSON_EXTRACT_SCALAR(data, '$.campaign'), "") as campaign, -- UTM
  NULLIF(JSON_EXTRACT_SCALAR(data, '$.clickId'), "") as clickId, -- UTM
  NULLIF(JSON_EXTRACT_SCALAR(data, '$.term'), "") as term, -- UTM
  NULLIF(JSON_EXTRACT_SCALAR(data, '$.referrer'), "") as referrer,
  NULLIF(JSON_EXTRACT_SCALAR(data, '$.storage'), "") as storage,
  NULLIF(JSON_EXTRACT_SCALAR(data, '$.isNew'), "") as is_new,
  NULLIF(JSON_EXTRACT_SCALAR(data, '$.count'), "") as count,
  data,
  NULLIF(JSON_EXTRACT_SCALAR(events.source, '$.id'), "") as source_id,
  NULLIF(JSON_EXTRACT_SCALAR(events.source, '$.previous_id'), "") as source_previous_id,
  event
    
  
FROM
  `api-project-726829680648.walkerOS.events` as events


WHERE
  1=1
  AND events.timestamp >= '2024-01-01'
  -- AND DATE(events.timestamp) >= DATE_SUB(CURRENT_DATE(), INTERVAL 2 DAY)
